timestamp: '2026-09-05T00:00:00'
joints:
  shoulder_pan:
    id: 1
    min:
      ticks: 797
      speed: 0
      load: 0
    center:
      ticks: 2048
      speed: 0
      load: 0
    max:
      ticks: 3495
      speed: 0
      load: 0
  shoulder_lift:
    id: 2
    min:
      ticks: 996
      speed: 0
      load: 0
    center:
      ticks: 2048
      speed: 0
      load: 0
    max:
      ticks: 3349
      speed: 0
      load: 0
  elbow_flex:
    id: 3
    min:
      ticks: 1002
      speed: 0
      load: 0
    center:
      ticks: 2048
      speed: 0
      load: 0
    max:
      ticks: 2951
      speed: 0
      load: 0
  elbow_rotate:
    id: 7
    min:
      ticks: 910
      speed: 0
      load: 0
    center:
      ticks: 2048
      speed: 0
      load: 0
    max:
      ticks: 3279
      speed: 0
      load: 0
  wrist_flex:
    id: 4
    min:
      ticks: 820
      speed: 0
      load: 0
    center:
      ticks: 2048
      speed: 0
      load: 0
    max:
      ticks: 3164
      speed: 0
      load: 0
  wrist_roll:
    id: 5
    min:
      ticks: 0
      speed: 0
      load: 0
    center:
      ticks: 2047
      speed: 0
      load: 0
    max:
      ticks: 4095
      speed: 0
      load: 0
  gripper:
    id: 6
    min:
      ticks: 2046
      speed: 0
      load: 0
    center:
      ticks: 2774
      speed: 0
      load: 0
    max:
      ticks: 3503
      speed: 0
      load: 0
