timestamp: '2026-06-04T00:00:00'
joints:
  shoulder_pan:
    min:
      ticks: 722
      speed: 0
      load: 0
    center:
      ticks: 2002
      speed: 0
      load: 0
    max:
      ticks: 3283
      speed: 0
      load: 0
  shoulder_lift:
    min:
      ticks: 769
      speed: 0
      load: 0
    center:
      ticks: 2040
      speed: 0
      load: 0
    max:
      ticks: 3312
      speed: 0
      load: 0
  elbow_flex:
    min:
      ticks: 751
      speed: 0
      load: 0
    center:
      ticks: 1898
      speed: 0
      load: 0
    max:
      ticks: 3046
      speed: 0
      load: 0
  wrist_flex:
    min:
      ticks: 840
      speed: 0
      load: 0
    center:
      ticks: 2031
      speed: 0
      load: 0
    max:
      ticks: 3223
      speed: 0
      load: 0
  wrist_roll:
    min:
      ticks: 0
      speed: 0
      load: 0
    center:
      ticks: 2047
      speed: 0
      load: 0
    max:
      ticks: 4095
      speed: 0
      load: 0
  gripper:
    min:
      ticks: 1550
      speed: 0
      load: 0
    center:
      ticks: 2346
      speed: 0
      load: 0
    max:
      ticks: 3142
      speed: 0
      load: 0
